### ISSUE TITLE
Byggprocess

### ISSUE THREAD

**Issue by ZetaTwo** [Fysiksektionen/Sangbok-Web#3]
Just nu är inte textfilerna i songdata-katalogen kopplade till databasen på något sätt utan ligger bara kvar som referens. Det betyder att ändringar i sånger måste göras på två ställen vilket är dåligt.

En lämplig lösning är att spara varje sång i ett något mer strukturerat filformat, t.ex. JSON och sen ha ett skript som bygger SQLite-databasen av alla textfiler. Då blir det smidigt att versionshantera alla sånger.

T.ex. berör detta https://github.com/Fysiksektionen/Sangbok-Web/pull/2 och https://github.com/Fysiksektionen/Sangbok-Web/pull/1

**Comment by tomasaschan** [comment]
Jag tycker idén är principiellt bra, men jag tror JSON är ett dåligt alternativ, främst för att det är onödigt svårt att redigera för hand. Två alternativa förslag:
- **Markdown:**  
  Fördelar:
  - Lätt att läsa och redigera i råtext
  - Lätt att få in specialformateringar i olika sånger, t.ex. för kommentarer om hur sångerna ska framföras eller om upphovsmän, trots att den informationen kan vara svår att strukturera i ett antal informationsfält som är gemensamma för alla sånger.
  - GitHub (och många text-editorer) har live-preview
  - Kan på sikt sparas verbatim även i sql-databasen (och renderas till t.ex. html eller latex med tredjepartsverktyg)
  
  Nackdelar
  - Kanske inte strikt nog
- **Eget råtextformat**
  Alltså att t.ex. ha första raden som titel, sen en blankrad, sen ett antal stycken som blir "meta-info" (typ upphov, kommentarer om sångsätt etc) sen två blankrader, sen sångtexten etc.  
  Fördelar:
  - Ger oss möjlighet att göra en lagom trade-off mellan flexibilitet och enkelhet  
  
  Nackdelar:
  - Ev. oförutsägbart för den som redigerar texten, vilket gör det svårare för icke-insatta att bidra med förbättringar

**Comment by tomasaschan** [comment]
Btw, är CI en egen grej, eller vill vi inkludera det i den här issuen?

**Comment by ZetaTwo** [comment]
Man kan göra som t.ex. Jekyll och ha Markdown med en "front matter" dvs ett
kort segment avgränsat med typ streck men key-value data och sen själva
texten då som Markdown.

CI kan nog läggas som en egen issue. Iom att det just nu inte finns något
så är de inte på förhand direkt beroende av varandra.
fre 19 aug. 2016 kl. 21:19 skrev Tomas Lycken notifications@github.com:

**Comment by tomasaschan** [comment]
Det låter som en rätt nice plan. Metadata i YAML? Hur kan jag vara behjälplig?

**Comment by ZetaTwo** [comment]
Som jag ser det är det typ följande delsteg:
1. Välja ett språk att implementera detta i
2. Hitta ett lämpligt front-matter lib. Verkar finnas massor.
3. Besluta om filformat och konvertera alla filer.
4. Skapa ett byggskript som gör en SQLite-db av filerna.

Gällande 1 så tycker jag att det finns två val: PHP, för att resten är skrivet i det, och Python för att det är vad alla på fysik får lära sig.

**Comment by ZetaTwo** [comment]
Fixat i 5101cc30edcb44fa5d08dd9d7672aa2302e313f4¨
Har uppdaterat README för att reflektera.
